#!/bin/sh
python setup.py install
python *.py
./configure || ./autogen.sh && ./configure || autoreconf -i && ./configure
make && make check ; make install || sudo make install || su -c 'make install'
echo 'done'