valgrind -v ./ex1
valgrind -v ./ex2
valgrind -v ./ex3
valgrind -v ./ex4
valgrind -v ./ex5
valgrind -v ./ex6
valgrind -v ./ex7
valgrind -v ./ex8
valgrind -v ./ex9
valgrind -v ./ex10
valgrind -v ./ex11
valgrind -v ./ex12
valgrind -v ./ex13
valgrind -v ./ex14
valgrind -v ./ex15
valgrind -v ./ex16
valgrind -v ./ex17
